linters-settings:
  # Specify your linters and their settings here
  golint:
    enabled: true
  govet:
    enabled: true
  staticcheck:
    enabled: true
  line-length: 80


linters:
  enable:
    # Enable all linters by default
    - golint
    - govet
    - staticcheck
